---
- name: Run firewall script
  ansible.builtin.command: "{{ system_iptables_script_path }}"
  changed_when: true

- name: Restart docker
  ansible.builtin.service:
    name: docker
    state: restarted
    enabled: true
